spring.application.name=back

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d6l5t9lm5p6s7396skag-a.oregon-postgres.render.com:5432/renderdatabase_9ioa
spring.datasource.username=renderdatabase_9ioa_user
spring.datasource.password=RPjd5xdq2mD8qkXLCykKGZc6o84ZiHl2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true